### ISSUE TITLE
Name for db_name is deprecated

### ISSUE THREAD

**Issue by piotrek660** [snowplow-devops/terraform-aws-rds#11]
Hi, 

there was a change in aws_db_instance for the name of the db, name is deprecated:

│ Warning: Argument is deprecated
│ 
│   with module.iglu_rds.aws_db_instance.instance,
│   on .terraform/modules/iglu_rds/main.tf line 42, in resource "aws_db_instance" "instance":
│   42:   name     = var.db_name
│ 
│ Use db_name instead

see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance

**Comment by angelsk** [comment]
Just to add, this is for AWS version 4+ (I believe the repo is still set for AWS version 3+)

Though I would also like this config change :)
