### ISSUE TITLE
Versioning of modules

### ISSUE THREAD

**Issue by OlesYudin** [snowplow-devops/terraform-aws-rds#18]
I have a problem with module versioning. I want to use the latest version of this module but in version 0.4.0 authors change the version of terraform to 4.0.
If you check other snowplow modules use will see that most of the modules use the version of Terraform 3+.
So, here is a problem, you can not use most parts of the snowplow modules because part of them use Terraform 3+ and some parts use Terraform 4+. I think if you want to move to terraform 4+ you should label the release as 1.X.X but not 0.4.X because the first number of versions it's about the major version.

**Comment by jbeemster** [comment]
Hi @OlesYudin so all of the Snowplow modules are compatible with AWS Provider v4+ - there should not be any issues with the latest Snowplow modules and using AWS Provider v4+ across the board.

In terms of following SemVer none of these modules have reached a maturity level yet where we have classed any of them as a `1.0.0` so for the moment breaking changes are only triggering a `minor` version bump.

**Comment by OlesYudin** [comment]
> Hi @OlesYudin so all of the Snowplow modules are compatible with AWS Provider v4+ - there should not be any issues with the latest Snowplow modules and using AWS Provider v4+ across the board.
> 
> In terms of following SemVer none of these modules have reached a maturity level yet where we have classed any of them as a `1.0.0` so for the moment breaking changes are only triggering a `minor` version bump.

Thank you for your answer
